---
# <% load "#{File.dirname(__FILE__)}/test/integration/helpers/test_fixture_upload_helper.rb" %>
driver:
  name: vagrant

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: ubuntu-16.04
# Rasbpian jessie ~= debian 8.0
  - name: debian-8.1

suites:
  - name: default
    run_list:
      - recipe[lyraphase-pi::default]
    attributes:
  - name: wifi-bridge
    run_list:
      - recipe[lyraphase-pi::wifi-bridge]
    attributes:
      lyraphase-pi:
        wifi-bridge:
          parprouted:
            skip_wireless_ip_clone: true
