## If you want to use one of the kitchen-docker* drivers...
## You should symlink this file to: .kitchen.local.yml
## Hint: Make sure you have kitchen-docker and kitchen-docker-api gems installed
## Then set DOCKER_HOST=tcp://my-docker-host.example.com:4243
---
## driver name: docker is for portertech/kitchen-docker
driver:
  name: docker
## driver_plugin: docker is for adnichols/kitchen-docker-api

driver_config:
  hostname: kitchen
#  use_sudo: true
  socket: <%= ENV['DOCKER_HOST'] %>
  privileged: true
  cap_add:
    - SYS_ADMIN
    - NET_ADMIN
    - NET_BIND_SERVICE
    - NET_BROADCAST

platforms:
- name: debian-8.1
- name: ubuntu-16.04
