language: ruby

rvm:
- 2.2.3

bundler_args: --without development

sudo: required
#sudo: false

env:
  matrix:
# Split up the test-kitchen run to avoid exceeding 50 minutes:
# And speed things up by paralellizing test-kitchen platforms
  - TEST_TYPE=integration KITCHEN_REGEXP=default-debian
  - TEST_TYPE=integration KITCHEN_REGEXP=default-ubuntu
  - TEST_TYPE=integration KITCHEN_REGEXP='(?<!default)-debian'
  - TEST_TYPE=integration KITCHEN_REGEXP='(?<!default)-ubuntu'
  - TEST_TYPE=unit
#env:
#  global:
#  - PATH="/opt/chefdk/bin:/opt/chef/bin:/opt/chef/embedded/bin:/opt/chefdk/embedded/bin:$PATH"

#addons:
#  apt:
#    sources:
#    - chef-stable-precise
#    packages:
#    - chefdk

before_script:
- source <(curl -sL https://raw.githubusercontent.com/zuazo/kitchen-in-travis/0.5.0/scripts/start_docker.sh)
# - eval "$(chef shell-init $(basename $SHELL))"

script:
  - '[[ "$TEST_TYPE" == "unit" ]] && bundle exec rake travis || true'
  - '[[ "$TEST_TYPE" == "integration" ]] && travis_retry travis_wait bundle exec rake integration:docker[$KITCHEN_REGEXP] || true'
