language: ruby

rvm:
- 2.0.0
- 2.1
- 2.2

sudo: false

#env:
#  global:
#  - PATH="/opt/chefdk/bin:/opt/chef/bin:/opt/chef/embedded/bin:/opt/chefdk/embedded/bin:$PATH"

#addons:
#  apt:
#    sources:
#    - chef-stable-precise
#    packages:
#    - chefdk

before_script:
- source <(curl -sL https://raw.githubusercontent.com/zuazo/kitchen-in-travis/0.5.0/scripts/start_docker.sh)
# - eval "$(chef shell-init $(basename $SHELL))"

script:
  - travis_retry bundle exec rake travis

