name 'lyraphase-pi'
maintainer 'James Cuzella'
maintainer_email 'james.cuzella@lyraphase.com'
license 'gplv3'
description 'Installs/Configures lyraphase-pi'
long_description 'Installs/Configures lyraphase-pi'
version '0.2.0'
issues_url 'https://github.com/trinitronx/lyraphase-pi/issues'
source_url 'https://github.com/trinitronx/lyraphase-pi'

supports 'debian'
depends 'sysctl', '~> 0.7'
